spring:
  application:
    name: exchange-rate-api
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ex_db
    username: root

exchange-rate:
  naver:
    host: https://m.search.naver.com
    url: /p/csearch/content/qapirender.nhn
    request-param:
      key: calculator
      pkid: 141
      q: "%ED%99%98%EC%9C%A8"
      where: m
      u1: keb
      u6: standardUnit
      u7: 0
      u3: USD
      u4: KRW
      u8: down
      u2: 1